# Generated by Django 5.1.4 on 2024-12-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotemplate',
            name='multimedia_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
