# Generated by Django 5.1.4 on 2024-12-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_portfoliotemplate_multimedia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotemplate',
            name='certifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliotemplate',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
