# Generated by Django 5.1.4 on 2024-12-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_portfoliotemplate_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotemplate',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
