# Generated by Django 5.1.4 on 2024-12-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_alter_portfoliotemplate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotemplate',
            name='code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
